title: Vocalin
description: Documentation for Vocalin
theme: just-the-docs
url: https://vocalin.github.io

nav_order: 1
nav:
  - title: "Home"
    url: /
  - title: "Speech Synthesis Markup Language"
    url: /ssml
